#!/bin/tcsh
#
# This is a StarExec runscript for PyCheck. See https://www.starexec.org.
#
# To use this, build a StarExec package with "make starexec" and
# upload it to a StarExec cluster - then follow local instructions
# ;-).
#

# module add python/python33
set flags=""
set final=" "$1
set cmd="./pycheck.py -e./eprover $flags $final"

echo "% Command    : " $cmd
/home/starexec/bin/GetComputerInfo -p THIS Model CPUModel RAMPerCPU OS | \
sed -e "s/Computer     /% Computer   /" \
    -e "s/Model        /% Model      /" \
    -e "s/CPUModel     /% CPU        /" \
    -e "s/RAMPerCPU    /% Memory     /" \
    -e "s/OS           /% OS         /"
echo -n "% CPULimit   : " ; echo "$STAREXEC_CPU_LIMIT"
echo -n "% DateTime   : " ; date
echo "% CPUTime    : "
$cmd
